CREATE TABLE IF NOT EXISTS bookings (
    id VARCHAR(50) PRIMARY KEY, -- Format: FPT-1001
    user_id UUID NOT NULL, -- Reference to customer-service
    car_id UUID NOT NULL, -- Reference to car-service
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    pickup_location VARCHAR(255) NOT NULL,
    dropoff_location VARCHAR(255) NOT NULL,
    total_amount DECIMAL(15,2) NOT NULL,
    deposit_amount DECIMAL(15,2) NOT NULL,
    payment_method VARCHAR(50) NOT NULL, -- TRANSFER, CASH, CREDIT_CARD
    booking_status VARCHAR(50) NOT NULL, -- INITIATED, CONFIRMED, APPROVED, ACTIVE, COMPLETED, CANCELLED, CANCELLED_DUE_TO_CAR, CANCELLED_DUE_TO_CUSTOMER
    payment_status VARCHAR(50) NOT NULL, -- UNPAID, PARTIALLY_PAID, FULLY_PAID, REFUNDED
    renter_name VARCHAR(255) NOT NULL,
    renter_phone VARCHAR(50) NOT NULL,
    renter_cccd VARCHAR(50) NOT NULL,
    renter_license VARCHAR(50) NOT NULL,
    customer_note TEXT,
    admin_note TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS booking_saga_logs (
    id UUID PRIMARY KEY,
    booking_id VARCHAR(50) NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    current_step VARCHAR(50) NOT NULL, -- RESERVE_CAR, CHECK_CUSTOMER_LIMIT, COMPLETE
    saga_status VARCHAR(50) NOT NULL, -- STARTED, COMPLETED, ABORTED, ROLLING_BACK, ROLLED_BACK
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
