# Trong Config Repo -> application.yml (File Global)
app:
  jwtSecret: ${JWT_SECRET:FPTCarRentingSecretKeyDungDeKyTokenPhaiDuDaiDeBaoMat2026}
  jwtExpirationMs: 86400000 # 24 giờ

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:demo}
  api-key: ${CLOUDINARY_API_KEY:demo}
  api-secret: ${CLOUDINARY_API_SECRET:demo}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

