server:
  port: 8084

spring:
  application:
    name: renting-service
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  datasource:
    url: jdbc:postgresql://${RENTING_DB_HOST:localhost}:${RENTING_DB_PORT:5432}/${RENTING_DB_NAME:rental_db}
    username: ${RENTING_DB_USERNAME:postgres}
    password: ${RENTING_DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate.format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/